linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - golint
    - gofumpt
    - goerr113
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - nonamedreturns
    - nosnakecase
    - structcheck
    - scopelint
    - testpackage
    - varcheck
    # Disabled because of generics support. See https://github.com/golangci/golangci-lint/issues/2649.
    - rowserrcheck
    - wastedassign
linters-settings:
  cyclop:
    max-complexity: 12
    skip-tests: true
  gomnd:
    ignored-functions:
      - 'math.*'
  paralleltest:
    ignore-missing: true
  varnamelen:
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
    ignore-decls:
      - c echo.Context
      - t testing.T
      - f *foo.Bar
      - e error
      - i int
      - const C
      - T any
      - K any
      - V any
      - m map[string]int
