// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/surahman/FTeX/pkg/postgres"
)

type FiatExchangeTransferResponse struct {
	SourceReceipt      *postgres.FiatAccountTransferResult `json:"sourceReceipt"`
	DestinationReceipt *postgres.FiatAccountTransferResult `json:"destinationReceipt"`
}

type FiatOpenAccountResponse struct {
	ClientID string `json:"clientID"`
	Currency string `json:"currency"`
}
