server:
  portNumber: 33723
  basePath: api/rest/v1
  swaggerPath: /swagger/*any
  shutdownDelay: 5s
  readTimeout: 1s
  writeTimeout: 1s
  readHeaderTimeout: 1s
authorization:
  headerKey: Authorization
