fiatCurrency:
  apiKey: some-api-key-for-fiat-currencies
  endpoint: https://api.apilayer.com/exchangerates_data/convert?to={to}&from={from}&amount={amount}
cryptoCurrency:
  apiKey: some-api-key-for-crypto-currencies
  endpoint: url-to-data-source-for-crypto-currency-price-quotes
connection:
  userAgent: ftex_inc
  timeout: 1s
