// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: crypto.sql

package postgres

import (
	"context"

	"github.com/gofrs/uuid"
)

const cryptoCreateAccount = `-- name: cryptoCreateAccount :execrows
INSERT INTO crypto_accounts (client_id, ticker)
VALUES ($1, $2)
`

type cryptoCreateAccountParams struct {
	ClientID uuid.UUID `json:"clientID"`
	Ticker   string    `json:"ticker"`
}

// cryptoCreateAccount inserts a fiat account record.
func (q *Queries) cryptoCreateAccount(ctx context.Context, arg *cryptoCreateAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, cryptoCreateAccount, arg.ClientID, arg.Ticker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
