// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: udf.sql

package postgres

import (
	"context"

	"github.com/shopspring/decimal"
)

const testRoundHalfEven = `-- name: testRoundHalfEven :one
SELECT round_half_even($1, $2)
`

type testRoundHalfEvenParams struct {
	Num   decimal.Decimal `json:"num"`
	Scale int32           `json:"scale"`
}

// testRoundHalfEven
func (q *Queries) testRoundHalfEven(ctx context.Context, arg *testRoundHalfEvenParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, testRoundHalfEven, arg.Num, arg.Scale)
	var round_half_even decimal.Decimal
	err := row.Scan(&round_half_even)
	return round_half_even, err
}
