// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: createUser :one
INSERT INTO users (username, password, first_name, last_name, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING client_id
`

type createUserParams struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

// createUser will create a new user record.
func (q *Queries) createUser(ctx context.Context, arg createUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Email,
	)
	var client_id pgtype.UUID
	err := row.Scan(&client_id)
	return client_id, err
}

const deleteUser = `-- name: deleteUser :execresult
UPDATE users
SET is_deleted=true
WHERE username=$1 AND is_deleted=false
`

// deleteUser will soft delete a users account.
func (q *Queries) deleteUser(ctx context.Context, username string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUser, username)
}

const getClientIdUser = `-- name: getClientIdUser :one
SELECT client_id
FROM users
WHERE username=$1
LIMIT 1
`

// getClientIdUser will retrieve a users client id.
func (q *Queries) getClientIdUser(ctx context.Context, username string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getClientIdUser, username)
	var client_id pgtype.UUID
	err := row.Scan(&client_id)
	return client_id, err
}

const getCredentialsUser = `-- name: getCredentialsUser :one
SELECT client_id, password
FROM users
WHERE username=$1 AND is_deleted=false
LIMIT 1
`

type getCredentialsUserRow struct {
	ClientID pgtype.UUID `json:"clientID"`
	Password string      `json:"password"`
}

// getCredentialsUser will retrieve a users client id and password.
func (q *Queries) getCredentialsUser(ctx context.Context, username string) (getCredentialsUserRow, error) {
	row := q.db.QueryRow(ctx, getCredentialsUser, username)
	var i getCredentialsUserRow
	err := row.Scan(&i.ClientID, &i.Password)
	return i, err
}

const getInfoUser = `-- name: getInfoUser :one
SELECT first_name, last_name, email, client_id, is_deleted
FROM users
WHERE username=$1
LIMIT 1
`

type getInfoUserRow struct {
	FirstName string      `json:"firstName"`
	LastName  string      `json:"lastName"`
	Email     string      `json:"email"`
	ClientID  pgtype.UUID `json:"clientID"`
	IsDeleted bool        `json:"isDeleted"`
}

// getInfoUser will retrieve a single users account information.
func (q *Queries) getInfoUser(ctx context.Context, username string) (getInfoUserRow, error) {
	row := q.db.QueryRow(ctx, getInfoUser, username)
	var i getInfoUserRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ClientID,
		&i.IsDeleted,
	)
	return i, err
}
