name: 'Golang Setup'
description: 'Configures Golang tooling and dependency caches.'
runs:
  using: "composite"
  steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
      id: go

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
