name: CI

on:
  push:
    branches:
      - development
      - production
  pull_request:
    branches:
      - development
      - production
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS_CI: true

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: "ftex_db_test"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Liquibase database migration
        uses: liquibase/liquibase-github-action@v7
        with:
          operation: 'update'
          classpath: 'pkg/models/postgres'
          changeLogFile: 'schema_github_actions.sql'
          username: postgres
          password: postgres
          url: 'jdbc:postgresql://postgres:5432/ftex_db_test'

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
          check-latest: true
          cache: true
        id: go

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Unit Test
        run: make test
